name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-sidebar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm i docsify-tools

      - name: Make Sidebar
        run: npm test

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-updated Sidebar
